services:
  yasmine-frontend:
    image: iris-edu/yasmine-stationxml-editor
    container_name: yasmine-frontend
    build:
      network: host
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "1841:1841"
    volumes:
      - ./:/code
    networks:
      - yasmine
  yasmine-backend:
    container_name: yasmine-backend
    build:
      network: host
      context: ./backend
      dockerfile: ./Dockerfile
    image: yasmine/backend
    ports:
      - "80:80"
    volumes:
      - yasmine-backend:/opt/yasmine
      - ./backend:/opt/yasmine/src
    networks:
      - yasmine
    stdin_open: true
    tty: true
volumes:
  yasmine-backend:
networks:
  yasmine: {}
