version: '3'
services:
    yasmine-frontend:
        container_name: yasmine-frontend
        build: frontend
        image: yasmine/frontend
        platform: linux/arm64/v8
        ports:
            - "1841:1841"   
        volumes:
            - ./:/code
        networks:
            - yasmine
    yasmine-backend:
        container_name: yasmine-backend
        build: backend
        image: yasmine/backend
        platform: linux/amd64
        ports:
            - "8080:80"
        volumes:
            - ./data:/opt/yasmine/data
            - ./backend:/opt/yasmine/src  
        networks:
            - yasmine             
        stdin_open: true
        tty: true        
networks: 
    yasmine:
