#@PydevCodeAnalysisIgnore
"""add_water_level_attr

Revision ID: 0bbe624e28b8
Revises: 65a56457757f
Create Date: 2020-12-18 11:58:29.886532

"""
from alembic import op
from sqlalchemy.orm.session import Session
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from yasmine.app.enums.xml_node import XmlNodeEnum
from yasmine.app.models import XmlNodeAttrModel, XmlNodeAttrWidgetModel, XmlNodeModel, XmlNodeAttrRelationModel

revision = '0bbe624e28b8'
down_revision = '65a56457757f'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)
    float_field = session\
        .query(XmlNodeAttrWidgetModel)\
        .filter(XmlNodeAttrWidgetModel.name == 'yasmine-float-field')\
        .first()
    water_level = XmlNodeAttrModel(name='water_level', widget=float_field, index=100)

    station = session.query(XmlNodeModel).get(XmlNodeEnum.STATION)
    station.attrs.append(XmlNodeAttrRelationModel(attr=water_level))

    channel = session.query(XmlNodeModel).get(XmlNodeEnum.CHANNEL)
    channel.attrs.append(XmlNodeAttrRelationModel(attr=water_level))

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
