#@PydevCodeAnalysisIgnore
"""add_station_restricted_field

Revision ID: 0f905a6d7295
Revises: 81e1ccb617ce
Create Date: 2021-03-11 16:08:20.723750

"""
from alembic import op
from sqlalchemy.orm.session import Session
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from yasmine.app.models import XmlNodeAttrWidgetModel, XmlNodeAttrModel

revision = '0f905a6d7295'
down_revision = '81e1ccb617ce'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)
    status_field = XmlNodeAttrWidgetModel(name='yasmine-restricted-status-field')
    session.add(status_field)
    session.commit()

    restricted_status = session\
        .query(XmlNodeAttrModel)\
        .filter(XmlNodeAttrModel.name == 'restricted_status')\
        .first()

    restricted_status.widget_id = status_field.id
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
