# @PydevCodeAnalysisIgnore
"""remove_creation_date_from_required

Revision ID: 17ca3221abc2
Revises: b7c9a0eae67b
Create Date: 2020-12-23 13:43:43.865336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
import pickle

# revision identifiers, used by Alembic.
from yasmine.app.models import ConfigModel

revision = '17ca3221abc2'
down_revision = 'b7c9a0eae67b'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    session.query(ConfigModel) \
        .filter(ConfigModel.group == 'station', ConfigModel.name == 'required_fields') \
        .update({'value': pickle.dumps(['code', 'latitude', 'longitude', 'elevation', 'site'])})

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
