#@PydevCodeAnalysisIgnore
"""remove_storage_format_attribute

Revision ID: 641838adfe95
Revises: 2903a91a0ba5
Create Date: 2020-12-17 16:29:30.480469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session


# revision identifiers, used by Alembic.
from yasmine.app.models import XmlNodeAttrModel

revision = '641838adfe95'
down_revision = '2903a91a0ba5'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    session.query(XmlNodeAttrModel).filter(XmlNodeAttrModel.name == 'storage_format').delete()

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
