#@PydevCodeAnalysisIgnore
"""rename_equipment

Revision ID: 65a56457757f
Revises: 641838adfe95
Create Date: 2020-12-18 09:33:37.226387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session
from yasmine.app.models import XmlNodeAttrModel

# revision identifiers, used by Alembic.
revision = '65a56457757f'
down_revision = '641838adfe95'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    session.query(XmlNodeAttrModel).filter(XmlNodeAttrModel.name == 'equipment').update({'name': 'equipments'})

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
