#@PydevCodeAnalysisIgnore
"""clean_database

Revision ID: 81e1ccb617ce
Revises: a30b33c0e533
Create Date: 2021-01-05 10:57:00.509613

"""
from alembic import op
from sqlalchemy.orm.session import Session
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from yasmine.app.models import UserLibraryModel, XmlNodeAttrValModel, XmlNodeInstModel, XmlModel

revision = '81e1ccb617ce'
down_revision = 'a30b33c0e533'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)
    session.query(XmlNodeAttrValModel).delete()
    session.query(XmlNodeInstModel).delete()
    session.query(UserLibraryModel).delete()
    session.query(XmlModel).delete()
    session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
