#@PydevCodeAnalysisIgnore
"""add_equipments_attr

Revision ID: a30b33c0e533
Revises: 17ca3221abc2
Create Date: 2020-12-23 19:00:27.197782

"""
from alembic import op
from sqlalchemy.orm.session import Session
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from yasmine.app.enums.xml_node import XmlNodeEnum
from yasmine.app.models import XmlNodeAttrWidgetModel, XmlNodeAttrModel, XmlNodeModel, XmlNodeAttrRelationModel

revision = 'a30b33c0e533'
down_revision = '17ca3221abc2'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    equipments_field = XmlNodeAttrWidgetModel(name='yasmine-equipments-field')
    session.add(equipments_field)
    session.commit()

    equipments = session\
        .query(XmlNodeAttrModel)\
        .filter(XmlNodeAttrModel.name == 'equipments')\
        .first()

    equipments.widget_id = equipments_field.id

    station = session.query(XmlNodeModel).get(XmlNodeEnum.STATION)
    station.attrs.append(XmlNodeAttrRelationModel(attr=equipments))
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
