#@PydevCodeAnalysisIgnore
"""add_operators_to_network

Revision ID: b7b613d93616
Revises: 0bbe624e28b8
Create Date: 2020-12-18 12:34:55.093317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

# revision identifiers, used by Alembic.
from yasmine.app.enums.xml_node import XmlNodeEnum
from yasmine.app.models import XmlNodeModel, XmlNodeAttrModel, XmlNodeAttrRelationModel

revision = 'b7b613d93616'
down_revision = '0bbe624e28b8'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    operators = session\
        .query(XmlNodeAttrModel)\
        .filter(XmlNodeAttrModel.name == 'operators')\
        .first()
    network = session.query(XmlNodeModel).get(XmlNodeEnum.NETWORK)
    network.attrs.append(XmlNodeAttrRelationModel(attr=operators))

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
