#@PydevCodeAnalysisIgnore
"""add_source_id_to_all

Revision ID: b7c9a0eae67b
Revises: 175699781887
Create Date: 2020-12-18 13:34:26.726679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session


# revision identifiers, used by Alembic.
from yasmine.app.enums.xml_node import XmlNodeEnum
from yasmine.app.models import XmlNodeAttrWidgetModel, XmlNodeAttrModel, XmlNodeAttrRelationModel, XmlNodeModel

revision = 'b7c9a0eae67b'
down_revision = '175699781887'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    source_id_field = session \
        .query(XmlNodeAttrWidgetModel) \
        .filter(XmlNodeAttrWidgetModel.name == 'yasmine-text-field') \
        .first()

    source_id = XmlNodeAttrModel(name='source_id', widget=source_id_field, index=100)
    network = session.query(XmlNodeModel).get(XmlNodeEnum.NETWORK)
    network.attrs.append(XmlNodeAttrRelationModel(attr=source_id))
    station = session.query(XmlNodeModel).get(XmlNodeEnum.STATION)
    station.attrs.append(XmlNodeAttrRelationModel(attr=source_id))
    channel = session.query(XmlNodeModel).get(XmlNodeEnum.CHANNEL)
    channel.attrs.append(XmlNodeAttrRelationModel(attr=source_id))

    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
