# ****************************************************************************
#
# This file is part of the yasmine editing tool.
#
# yasmine (Yet Another Station Metadata INformation Editor), a tool to
# create and edit station metadata information in FDSN stationXML format,
# is a common development of IRIS and RESIF.
# Development and addition of new features is shared and agreed between * IRIS and RESIF.
#
#
# Version 1.0 of the software was funded by SAGE, a major facility fully
# funded by the National Science Foundation (EAR-1261681-SAGE),
# development done by ISTI and led by IRIS Data Services.
# Version 2.0 of the software was funded by CNRS and development led by * RESIF.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version. *
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License (GNU-LGPL) for more details. *
# You should have received a copy of the GNU Lesser General Public
# License along with this software. If not, see
# <https://www.gnu.org/licenses/>
#
#
# 2019/10/07 : version 2.0.0 initial commit
#
# ****************************************************************************/


#@PydevCodeAnalysisIgnore
"""add default GATITO url

Revision ID: cb0433358f3b
Revises: d691b46b63c2
Create Date: 2019-11-22 13:02:56.832383

"""
from alembic import op
import sqlalchemy as sa
import pickle
from sqlalchemy.orm.session import Session


# revision identifiers, used by Alembic.
from yasmine.app.models import ConfigModel

revision = 'cb0433358f3b'
down_revision = 'd691b46b63c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_xml_node_instance_id'), 'xml_node_instance', ['id'], unique=True)
    op.drop_index('ix_xml_node_instance2_id', table_name='xml_node_instance')

    bind = op.get_bind()
    session = Session(bind=bind)
    session.query(ConfigModel)\
        .filter(ConfigModel.name == 'user_library_source_url')\
        .update({'value': pickle.dumps('https://gitlab.com/resif/gatito/-/archive/master/gatito-master.zip')})
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_xml_node_instance2_id', 'xml_node_instance', ['id'], unique=1)
    op.drop_index(op.f('ix_xml_node_instance_id'), table_name='xml_node_instance')
    # ### end Alembic commands ###
