# ****************************************************************************
#
# This file is part of the yasmine editing tool.
#
# yasmine (Yet Another Station Metadata INformation Editor), a tool to
# create and edit station metadata information in FDSN stationXML format,
# is a common development of IRIS and RESIF.
# Development and addition of new features is shared and agreed between * IRIS and RESIF.
#
#
# Version 1.0 of the software was funded by SAGE, a major facility fully
# funded by the National Science Foundation (EAR-1261681-SAGE),
# development done by ISTI and led by IRIS Data Services.
# Version 2.0 of the software was funded by CNRS and development led by * RESIF.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version. *
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License (GNU-LGPL) for more details. *
# You should have received a copy of the GNU Lesser General Public
# License along with this software. If not, see
# <https://www.gnu.org/licenses/>
#
#
# 2019/10/07 : version 2.0.0 initial commit
#
# ****************************************************************************/


#@PydevCodeAnalysisIgnore
"""empty message

Revision ID: d3772e3014d4
Revises: aacf65cac9db
Create Date: 2019-10-17 11:24:21.718777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.orm import Session

from yasmine.app.models import XmlNodeAttrValModel

revision = 'd3772e3014d4'
down_revision = 'aacf65cac9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table('xml_node_attr_value2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('node_inst_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['xml_node_attribute.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['xml_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_inst_id'], ['xml_node_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xml_node_attr_value2_id'), 'xml_node_attr_value2', ['id'], unique=True)
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = Session(bind=bind)
    query = session.query(
        XmlNodeAttrValModel.id,
        XmlNodeAttrValModel.value,
        XmlNodeAttrValModel.attr_id,
        XmlNodeAttrValModel.node_inst_id)
    for row in query:
        session.execute(table.insert(row))
    session.commit()

    op.drop_table('xml_node_attr_value')
    op.rename_table('xml_node_attr_value2', 'xml_node_attr_value')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
