name: Yasmine
on: [ push ]
jobs:
#  lint_python:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Python 3.6
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.6.x'
#      - run: pip install pep8
#      - run: pep8 backend/yasmine

  build_app:
    runs-on: ubuntu-latest
    container: ghcr.io/iris-edu/yasmine-stationxml-editor/yasmine-utils:latest
    steps:
      - run: sencha --version





#  docker:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#    steps:
#      - name: Check Out Repo
#        uses: actions/checkout@v2
#
#      - name: Log in to registry
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
#
#      - name: Build image
#        run: docker build . --file docker-gitlab-centos7 --tag ghcr.io/iris-edu/yasmine-stationxml-editor/yasmine-utils:latest
#
#      - name: Push image
#        run: docker push ghcr.io/iris-edu/yasmine-stationxml-editor/yasmine-utils:latest
